name: Ubuntu SSH

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/sushrut1101/docker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh > /tmp/ssh.txt
          cat /tmp/ssh.txt
      
      - name: Spam
        run: |
          sudo bash spam.sh
